run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - pip install -r src/requirements.txt
    - apt-get update && apt-get -y install make git
    - source src/.venv/bin/activate && pytest -v
  script:
  - make test